version: "2"
services:
  stack-builder:
    image: bde2020/ember-stack-builder-frontend:0.2.5
    ports:
      - 13337:80
    links:
      - identifier:backend

  pipeline-builder:
    image: bde2020/pipeline-builder-frontend:0.4.2
    links:
      - identifier:backend
    ports:
      - 13338:80

  swarm-ui:
    image: bde2020/ember-swarm-ui-frontend:0.4.3
    ports:
      - 13339:80
    links:
      - identifier:backend
    volumes:
      - ./config/frontend:/etc/nginx/conf.d

  integrator-ui:
    build: ./integrator-ui
    ports:
      - 80:80

  identifier:
    image: semtech/mu-identifier:1.2.0
    links:
      - dispatcher:dispatcher
      - swarm:swarm-admin

  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  database:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/toLoad:/data/toLoad

  resource:
    image: semtech/mu-cl-resources:1.11.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config

  backend:
    image: bde2020/mu-docker-compose-file-service:0.1.0

  migrationsservice:
      image: semtech/mu-migrations-service
      volumes:
        - ./config/migrations:/data/migrations

  pipeline:
    image: bde2020/mu-pipeline-service:0.1.0

  export:
    image: bde2020/mu-pipeline-export-service:0.1.0

  swarm:
    image: bde2020/mu-swarm-admin-service:0.2.0
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - ENV=dev
    links:
      - database:database
      - docker:docker
    volumes:
      - /run/:/run/
      - /data/:/data/

  swarm-logger:
    build: ./mu-swarm-logger-service
    links:
      - database:database
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /src/run.py --debug sparql

  docker:
    image: docker:dind
    privileged: true
    volumes:
      - ./data/docker:/var/lib/docker

  event-query:
    build: ./mu-docker-event-query
    links:
      - database:database
    volumes:
      - ./containers:/usr/src/app/containers/
      - ./mu-docker-event-query/src:/app/
    environment:
      SLEEP_PERIOD: '10'

  docker-watcher:
    build: ./mu-docker-watcher
    volumes:
      - ./mu-docker-watcher/supervisord.conf:/etc/supervisord.conf
      - ./containers:/app/containers
      - ./pcap:/app/pcap/
    network_mode: host
    environment:
      PCAP_READ_DIR: '/pcap'

  har-transformation:
    build: ./mu-har-transformation
    volumes:
      - ./pcap:/app/pcap
      - ./har:/app/har
      - ./containers:/app/containers
    links:
      - elasticsearch:elasticsearch

  elasticsearch:
    image: elasticsearch:2
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"

  kibana:
    image: kibana:4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch:elasticsearch
