# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "2"
services:

  application:
    build:
      context: ./weblogic_app
      dockerfile: Dockerfile.real
    links:
      - frontend:backend
      - db:db
    volumes:
      - ./config:/config
    environment:
      JAVA_OPTIONS: -Xms1024m -Xmx3072m -XX:MaxPermSize=768m
      EXTRA_JAVA_PROPERTIES: -Dfile.encoding=UTF8 -Desco.configuration.properties.file=/config/config_db_virtuoso.properties -DCONFIG_DIR_DISPATCHER=/config/dispatcher -Dtenforce.ext.folder=/data -Dtenforce.ext.directory=/data -DCONFIG_DIR=/config
      MU_REPOSITORY_URL: http://db:8890
    ports:
      - 80:8001

  frontend:
    restart: always
    image: semtech/mu-nginx-spa-proxy
    volumes:
      - frontend-dist:/app
      - ./config/nginx:/etc/nginx/conf.d/
    links:
      - dispatcher:backend

  frontend-dist:
    build: ./client
    volumes:
      - frontend-dist:/app/dist
    # NOTE: the production version of the frontend is broken at the moment
    command: "ember build --dev"

  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - login:login
      - hierarchyapi:hierarchyapi
      - kpisapi:kpisapi
      - dictionary:dictionary
      - validation:validation
      - indexer:indexer
      - cleanup:cleanup
      - publisher:publisher
    volumes:
      - ./config:/config

  scheduler:
    build: ./mu-java-scheduler
    links:
      - dispatcher:dispatcher
    volumes:
      - ./config/scheduler:/config
    environment:
      BASE_URL: "http://dispatcher"

  db:
    image: tenforce/virtuoso:1.1.1-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/virtuoso:/var/lib/virtuoso/db
      - ./config/loader-service/data:/var/lib/virtuoso/db/toLoad
    ports:
      - "8890:8890"

  delta:
    build: ./mu-delta-service
    volumes:
      - ./config/delta-service:/config
    environment:
      CONFIGFILE: "/config/config.properties"
      SUBSCRIBERSFILE: "/config/subscribers.json"
    links:
      - db:db

  solr:
    build: ./solr-docker
    volumes:
      - /data/solr_home
    command: mvn jetty:run -Dsolr.port=8080

  indexer:
    build: ./delta-based-indexer
    ports:
      - "8894:8080"
    links:
      - solr:solr
      - db:database
    command: mvn spring-boot:run -D-Dsparql.namespace=http://mu.semte.ch/application -Dsparql.virtuoso.endpoint=http://database:8890/sparql/ -Dspring.data.solr.host=http://solr:8080/solr/collection1/ -Dqueues.enable=true

  resource:
    image: "semtech/mu-cache:0.4.0"
    links:
      - resourcebackend:backend
    environment:
      CACHE_BACKEND: "http://backend"

  resourcebackend:
    image: "semtech/mu-cl-resources:overeager-caching-tests"
    links:
      - delta:database
    volumes:
      - ./config/resources:/config
    environment:
      BOOT: mu-cl-resources

  hierarchyapi:
    build: ./hierarchy
    links:
      - db:database
    environment:
      HIER_CACHE_TIME: 0.01

  login:
    build: ./login
    links:
      - db:database
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/application"
      MU_APPLICATION_SALT: "KteCAqj7bAjEavWhUhUHL4oPFc3ePvVVMKgHKoh7nTqAvhRuatxoTkpnePrLPiWk"

  kpisapi:
    build: ./kpis
    links:
      - db:database

  dictionary:
    build: ./dictionary
    links:
      - db:database

  cleanup:
    build: ./clean-up-microservice
    volumes:
      - "./config/cleanup:/config"
    links:
      - db:database

  narrower-handler:
    build: ./narrower-handler
    links:
      - db:database

  publisher:
    build: ./publisher
    links:
      - db:database
    environment:
      MU_SPARQL_TIMEOUT: "1800"

  validation:
    build: ./validation
    links:
      - db:database
    environment:
      MU_SPARQL_TIMEOUT: "600"
    volumes:
      - "./config/validation:/config"

volumes:
  frontend-dist:
